heat_template_version: rocky

parameters:
  ServerDeletionPolicy:
    type: string
    default: delete
    constraints:
      - allowed_values: [delete, retain]
  Image:
    type: string
    default: overcloud-full
  Flavor:
    default: baremetal
    type: string
  KeyName:
    type: string
    default: default

resources:
  Server:
    type: OS::TripleO::Server
    deletion_policy: {get_param: ServerDeletionPolicy}
    properties:
      image: {get_param: Image}
      flavor: {get_param: Flavor}
      key_name: {get_param: KeyName}
      networks:
      - network: ctlplane
