heat_template_version: ocata

parameters:
  ServerDeletionPolicy:
    type: string
    default: delete
    constraints:
      - allowed_values: [delete, retain]
  Image:
    type: string
    default: CentOS-7-x86_64-GenericCloud-1804_02
  Flavor:
    default: m1.large
    type: string
  KeyName:
    type: string
    default: steveb

resources:
  Server:
    type: OS::TripleO::Server
    deletion_policy: {get_param: ServerDeletionPolicy}
    properties:
      image: {get_param: Image}
      flavor: {get_param: Flavor}
      key_name: {get_param: KeyName}